// apps/solid/src/App.tsx
import type { Component } from 'solid-js';
import { createSignal, For } from 'solid-js';
import todoStore from './lib/todoStore';
import './App.css';

type Todo = { text: string };

const App: Component = () => {
  let input: HTMLInputElement | undefined;
  const [newTodo, setNewTodo] = createSignal('');
  const { todos, setTodos } = todoStore;

  function addTodo() {
    if (!newTodo()) {
      return;
    }
    setTodos([...todos(), {text: newTodo()}]);
    setNewTodo('');
    input?.focus();
  }

  function removeTodo(todo: Todo) {
    setTodos(todos().filter(t => t !== todo));
  }

  return (
    <div id="app">
      <input ref={input} type="text" value={newTodo()} onInput={({target}) => setNewTodo(target.value)} placeholder="Add a new element"/>
      <button type="button" disabled={newTodo().length === 0} onClick={addTodo}>Add</button>

      <ul>
        <For each={todos()}>
          {(todo) => (
            <li>
                {todo.text}
                <button onClick={() => removeTodo(todo)}>x</button>
            </li>
          )}
        </For>
      </ul>
    </div>
  );
};

export default App;

// svelte/src/App.svelte
<script lang="ts">
    import {todoStore} from './lib/todoStore';

    let input: HTMLElement;
    let newTodo: string = '';

    function addTodo() {
        if (!newTodo) {
            return;
        }
        todoStore.update((todos) => [...todos, {text: newTodo}])
        newTodo = '';
        input.focus();
    }

    function removeTodo(todo) {
        todoStore.update((todos) => todos.filter(i => i !== todo));
    }
</script>

<input bind:this={input} type="text" bind:value={newTodo} placeholder="Add a new element"/>
<button type="button" disabled={newTodo.length === 0} on:click={addTodo}>Add</button>

<ul>
    {#each $todoStore as todo}
        <li>
            {todo.text}
            <button on:click={() => removeTodo(todo)}>x</button>
        </li>
    {/each}
</ul>
