// apps/vue-static-pnpm/src/App.vue
<script lang="ts">
    import {defineComponent} from 'vue';
    import {todoStore} from './lib/todoStore';

    export default defineComponent({
      name: 'App',
      data() {
        return {
          todoStore,
          newTodo: '',
        };
      },
      methods: {
        addTodo() {
          if (!this.newTodo) {
            return;
          }
          todoStore.update((todos: Array<{ text: string }>) => [...todos, {text: this.newTodo}])
          this.newTodo = '';
          ((this.$refs as any).input as HTMLInputElement).focus();
        },
        removeTodo(todo: { text: string }) {
          todoStore.update((todos: Array<{ text: string }>) => todos.filter(i => i !== todo));
        },
      },
    });
</script>

<template>
  <div id="app">
    <input type="text" ref="input" placeholder="Add a new element" v-model.trim="newTodo" />
    <button type="button" :disabled="this.newTodo.length === 0" @click="addTodo">Add</button>
    <ul>
      <li v-for="todo in todoStore.values">
        {{ todo.text }}
        <button @click="() => removeTodo(todo)">x</button>
      </li>
    </ul>
  </div>
</template>

// svelte/src/App.svelte
<script lang="ts">
    import {todoStore} from './lib/todoStore';

    let input: HTMLElement;
    let newTodo: string = '';

    function addTodo() {
        if (!newTodo) {
            return;
        }
        todoStore.update((todos) => [...todos, {text: newTodo}])
        newTodo = '';
        input.focus();
    }

    function removeTodo(todo) {
        todoStore.update((todos) => todos.filter(i => i !== todo));
    }
</script>

<input bind:this={input} type="text" bind:value={newTodo} placeholder="Add a new element"/>
<button type="button" disabled={newTodo.length === 0} on:click={addTodo}>Add</button>

<ul>
    {#each $todoStore as todo}
        <li>
            {todo.text}
            <button on:click={() => removeTodo(todo)}>x</button>
        </li>
    {/each}
</ul>
