// apps/angular-static-pnpm/src/app/app.component.ts
import { NgFor } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { getBaseValue, saveValue } from './store/store';

@Component({
  selector: 'app-root',
  template: `
    <div id="app">
      <input
        type="text"
        [(ngModel)]="newTodo"
        placeholder="Add a new element"
      />
      <button
        type="button"
        [disabled]="newTodo.length === 0"
        (click)="addTodo()"
      >
        Add
      </button>

      <ul>
        <li *ngFor="let todo of todos">
          {{ todo.text }}
          <button (click)="removeTodo(todo)">x</button>
        </li>
      </ul>
    </div>
  `,
  imports: [FormsModule, NgFor],
  standalone: true,
})
export class AppComponent {
  newTodo = '';
  todos: { text: string }[] = [];

  ngOnInit() {
    this.todos = getBaseValue();
  }

  addTodo() {
    this.todos.push({
      text: this.newTodo,
    });
    this.newTodo = '';

    saveValue(this.todos);
  }

  removeTodo(todo: { text: string }) {
    this.todos.splice(this.todos.indexOf(todo), 1);

    saveValue(this.todos);
  }
}

// apps/react-static-pnpm/src/App.js
import React, { useEffect, useState } from "react";
import { getBaseValue, saveValue, TodoContext } from "./store/TodoContext";
import './App.css';

function App() {
  const [newTodo, setNewTodo] = useState('');
  const [todos, setTodos] = useState(getBaseValue);

  useEffect(() => {
    saveValue(todos);
  }, [todos]);

  function addTodo () {
    setTodos([...todos, {text: newTodo}]);
    setNewTodo('');
  }

  function removeTodo (todo) {
    setTodos(todos.filter(t => t !== todo));
  }

  return (
      <div id="app">
          <TodoContext.Provider value={[todos, setTodos]}>
              <input type="text" value={newTodo} onChange={({target}) => setNewTodo(target.value)} placeholder="Add a new element"/>
              <button type="button" disabled={newTodo.length === 0} onClick={addTodo}>Add</button>

              <ul>
                  {todos.map((todo, index) => (
                      <li key={index}>
                          {todo.text}
                          <button onClick={() => removeTodo(todo)}>x</button>
                      </li>
                  ))}
              </ul>
          </TodoContext.Provider>
      </div>
  );
}

export default App;
