// vue-nuxt/pages/index.vue
<script lang="ts">
    import '../assets/main.css';
    import {defineComponent} from 'vue';
    import {todoStore} from '../lib/todoStore';

    export default defineComponent({
      name: 'App',
      data() {
        return {
          todoStore,
          newTodo: '',
        };
      },
      methods: {
        addTodo() {
          if (!this.newTodo) {
            return;
          }
          todoStore.update((todos: Array<{ text: string }>) => [...todos, {text: this.newTodo}])
          this.newTodo = '';
          (this.$refs.input as HTMLInputElement).focus();
        },
        removeTodo(todo: { text: string }) {
          todoStore.update((todos: Array<{ text: string }>) => todos.filter(i => i !== todo));
        },
      },
    });
</script>

<template>
  <div id="app">
    <input type="text" ref="input" placeholder="Add a new element" v-model.trim="newTodo" />
    <button type="button" :disabled="this.newTodo && this.newTodo.length === 0" @click="addTodo">Add</button>
    <ul>
      <li v-for="todo in todoStore.values">
        {{ todo.text }}
        <button @click="() => removeTodo(todo)">x</button>
      </li>
    </ul>
  </div>
</template>

// react-next/pages/index.tsx
import React, { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { getBaseValue, saveValue, TodoContext } from "../src/store/TodoContext";

const Home: NextPage = () => {
  const [newTodo, setNewTodo] = useState('');
  const [todos, setTodos] = useState<Array<{ text: string }>>(getBaseValue);

  useEffect(() => {
    saveValue(todos);
  }, [todos]);

  function addTodo () {
    setTodos([{text: newTodo}, ...todos]);
    setNewTodo('');
  }

  function removeTodo (todo: { text: string }) {
    setTodos(todos.filter((t: { text: string }) => t !== todo));
  }

  return (
    <TodoContext.Provider value={[todos, setTodos] as any}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vite.svg" />
      </Head>

      <div id="app">
        <input type="text" value={newTodo} onChange={({target}) => setNewTodo(target.value)} placeholder="Add a new element"/>
        <button type="button" disabled={newTodo.length === 0} onClick={addTodo}>Add</button>

        <ul>
          {todos.map((todo, index) => (
            <li key={index}>
              {todo.text}
              <button onClick={() => removeTodo(todo)}>X</button>
            </li>
          ))}
        </ul>
      </div>
    </TodoContext.Provider>
  );
}

export default Home
